#!/usr/bin/env python3
"""
JVM Core Dump / Crash Log analyzer.

Analyzes JVM crash artifacts:
- hs_err_pid*.log files (JVM fatal error logs) - text format, fully parsed
- .core files (ELF core dumps) - basic header analysis
- .mdmp files (Windows minidumps) - basic header analysis

For .core/.mdmp files, detailed analysis requires JDK tools (jhsdb, jstack).
This script extracts what it can from the binary headers and recommends
using JDK tools for full analysis.

Usage:
    python3 core_dump_analyzer.py <file>

The script auto-detects the file format and applies the appropriate parser.
"""

import json
import re
import struct
import sys
import os
from collections import Counter, defaultdict


def parse_hs_err_log(filepath):
    """Parse a JVM fatal error log (hs_err_pid*.log).
    
    These are text files generated by the JVM when it crashes.
    They contain extensive diagnostic information about the crash.
    """
    with open(filepath, 'r', errors='replace') as f:
        text = f.read()
    
    lines = text.split('\n')
    
    result = {
        'file': os.path.basename(filepath),
        'file_size_bytes': os.path.getsize(filepath),
        'type': 'hs_err_log',
    }
    
    # --- Error Summary ---
    error_summary = {}
    
    # Signal/exception type
    signal_match = re.search(r'#\s*(SIGSEGV|SIGBUS|SIGFPE|SIGILL|SIGABRT|EXCEPTION_ACCESS_VIOLATION|EXCEPTION_STACK_OVERFLOW|EXCEPTION_INT_DIVIDE_BY_ZERO)\s*\(([^)]*)\)\s*at\s*pc=(0x[0-9a-f]+)', text)
    if signal_match:
        error_summary['signal'] = signal_match.group(1)
        error_summary['signal_code'] = signal_match.group(2)
        error_summary['pc'] = signal_match.group(3)
    
    # Problematic frame
    frame_match = re.search(r'#\s*Problematic frame:\s*#\s*(.*)', text)
    if frame_match:
        error_summary['problematic_frame'] = frame_match.group(1).strip()
    
    # JRE version
    jre_match = re.search(r'#\s*JRE version:\s*(.*)', text)
    if jre_match:
        error_summary['jre_version'] = jre_match.group(1).strip()
    
    # Java VM
    vm_match = re.search(r'#\s*Java VM:\s*(.*)', text)
    if vm_match:
        error_summary['java_vm'] = vm_match.group(1).strip()
    
    # PID
    pid_match = re.search(r'pid=(\d+)', text)
    if pid_match:
        error_summary['pid'] = int(pid_match.group(1))
    
    result['error_summary'] = error_summary
    
    # --- Current Thread ---
    current_thread = {}
    ct_match = re.search(r'Current thread\s*\((0x[0-9a-f]+)\):\s*(\w+)\s+"([^"]*)"', text)
    if ct_match:
        current_thread['address'] = ct_match.group(1)
        current_thread['type'] = ct_match.group(2)
        current_thread['name'] = ct_match.group(3)
    
    # Thread state
    thread_state_match = re.search(r'Current thread.*\[([^\]]+)\]', text)
    if thread_state_match:
        current_thread['state'] = thread_state_match.group(1)
    
    result['current_thread'] = current_thread
    
    # --- Stack Trace ---
    stack_trace = []
    in_stack = False
    for line in lines:
        if 'Native frames:' in line or 'Java frames:' in line:
            in_stack = True
            continue
        if in_stack:
            stripped = line.strip()
            if stripped == '' or stripped.startswith('---'):
                if stack_trace:
                    break
                continue
            if stripped.startswith(('V ', 'v ', 'C ', 'j ', 'J ')):
                stack_trace.append(stripped)
    
    result['stack_trace'] = stack_trace[:30]  # Top 30 frames
    
    # --- VM State ---
    vm_state_match = re.search(r'VM state\s*:\s*(.*)', text)
    if vm_state_match:
        result['vm_state'] = vm_state_match.group(1).strip()
    
    # --- Thread List ---
    threads = []
    in_threads = False
    for line in lines:
        if line.strip().startswith('Threads class SMR info:') or 'Java Threads:' in line:
            in_threads = True
            continue
        if in_threads:
            thread_match = re.match(r'\s*(0x[0-9a-f]+)\s+(\w+)\s+"([^"]*)".*\[([^\]]*)\]', line)
            if thread_match:
                threads.append({
                    'address': thread_match.group(1),
                    'type': thread_match.group(2),
                    'name': thread_match.group(3),
                    'state': thread_match.group(4)
                })
            elif line.strip() == '' and threads:
                break
    
    result['thread_count'] = len(threads)
    
    # Thread state distribution
    if threads:
        state_counts = Counter(t['state'] for t in threads)
        result['thread_states'] = dict(state_counts.most_common())
    
    result['threads'] = threads[:50]  # First 50 threads
    
    # --- Heap Information ---
    heap_info = {}
    
    # Look for heap section
    heap_section = False
    for line in lines:
        if 'Heap:' in line or 'Heap' == line.strip():
            heap_section = True
            continue
        if heap_section:
            stripped = line.strip()
            if stripped == '':
                if heap_info:
                    break
                continue
            
            # Parse heap region info
            region_match = re.match(r'(\w[\w\s]*?):\s*total\s+(\d+\w?),\s*used\s+(\d+\w?)', stripped)
            if region_match:
                heap_info[region_match.group(1).strip()] = {
                    'total': region_match.group(2),
                    'used': region_match.group(3)
                }
            
            # Parse capacity/used/free
            cap_match = re.match(r'(\w[\w\s]*?)\s+capacity\s+(\d+),\s*used\s+(\d+)', stripped)
            if cap_match:
                heap_info[cap_match.group(1).strip()] = {
                    'capacity': int(cap_match.group(2)),
                    'used': int(cap_match.group(3))
                }
            
            # G1 format
            g1_match = re.match(r'(\w[\w\s]*?):\s*size\s+(\d+\w?),.*used\s+(\d+\w?)', stripped)
            if g1_match:
                heap_info[g1_match.group(1).strip()] = {
                    'size': g1_match.group(2),
                    'used': g1_match.group(3)
                }
    
    result['heap'] = heap_info
    
    # --- Memory Information ---
    memory_info = {}
    
    mem_match = re.search(r'Memory:\s*(\d+)k\s*page,\s*physical\s+(\d+)k\s*\((\d+)k\s*free\)', text)
    if mem_match:
        memory_info['page_size_k'] = int(mem_match.group(1))
        memory_info['physical_total_k'] = int(mem_match.group(2))
        memory_info['physical_free_k'] = int(mem_match.group(3))
        memory_info['physical_total_mb'] = round(int(mem_match.group(2)) / 1024, 1)
        memory_info['physical_free_mb'] = round(int(mem_match.group(3)) / 1024, 1)
    
    swap_match = re.search(r'swap\s+(\d+)k\s*\((\d+)k\s*free\)', text)
    if swap_match:
        memory_info['swap_total_k'] = int(swap_match.group(1))
        memory_info['swap_free_k'] = int(swap_match.group(2))
    
    result['memory'] = memory_info
    
    # --- VM Arguments ---
    vm_args = []
    vm_args_match = re.search(r'VM Arguments:\s*\n(.*?)(?:\n\n|\nTime:)', text, re.DOTALL)
    if vm_args_match:
        for line in vm_args_match.group(1).split('\n'):
            stripped = line.strip()
            if stripped.startswith('jvm_args:'):
                vm_args = stripped[len('jvm_args:'):].strip().split()
                break
    
    if vm_args:
        result['vm_arguments'] = vm_args
        
        # Extract key JVM flags
        heap_flags = {}
        for arg in vm_args:
            if arg.startswith('-Xmx'):
                heap_flags['max_heap'] = arg[4:]
            elif arg.startswith('-Xms'):
                heap_flags['initial_heap'] = arg[4:]
            elif arg.startswith('-Xss'):
                heap_flags['thread_stack'] = arg[4:]
            elif 'GC' in arg or 'gc' in arg:
                heap_flags['gc_flag'] = arg
        result['key_flags'] = heap_flags
    
    # --- Dynamic Libraries ---
    libs = []
    in_libs = False
    for line in lines:
        if 'Dynamic libraries:' in line:
            in_libs = True
            continue
        if in_libs:
            stripped = line.strip()
            if stripped == '' and libs:
                break
            if stripped and not stripped.startswith('VM state'):
                # Extract library path
                lib_match = re.search(r'(/\S+\.so[.\d]*|[A-Z]:\\.*\.dll)', stripped, re.IGNORECASE)
                if lib_match:
                    libs.append(lib_match.group(0))
    
    result['native_library_count'] = len(libs)
    result['native_libraries'] = libs[:30]  # First 30
    
    # --- Environment ---
    env_info = {}
    
    os_match = re.search(r'OS:\s*(.*)', text)
    if os_match:
        env_info['os'] = os_match.group(1).strip()
    
    cpu_match = re.search(r'CPU:\s*(.*)', text)
    if cpu_match:
        env_info['cpu'] = cpu_match.group(1).strip()
    
    uname_match = re.search(r'uname:\s*(.*)', text)
    if uname_match:
        env_info['uname'] = uname_match.group(1).strip()
    
    result['environment'] = env_info
    
    # --- Time of crash ---
    time_match = re.search(r'Time:\s*(.*)', text)
    if time_match:
        result['crash_time'] = time_match.group(1).strip()
    
    elapsed_match = re.search(r'elapsed time:\s*(\d+)\s*seconds', text)
    if elapsed_match:
        result['elapsed_seconds'] = int(elapsed_match.group(1))
    
    # --- Issue Detection ---
    issues = []
    
    signal = error_summary.get('signal', '')
    
    if signal == 'SIGSEGV':
        issues.append({
            'severity': 'CRITICAL',
            'category': 'crash',
            'message': f"Segmentation fault (SIGSEGV) at {error_summary.get('pc', '?')}. This is typically a JVM bug, native library issue, or hardware problem."
        })
    elif signal == 'SIGABRT':
        issues.append({
            'severity': 'CRITICAL',
            'category': 'crash',
            'message': "JVM aborted (SIGABRT). This often indicates an internal assertion failure or OOM."
        })
    elif 'EXCEPTION_STACK_OVERFLOW' in signal:
        issues.append({
            'severity': 'CRITICAL',
            'category': 'crash',
            'message': "Stack overflow crash. Thread stack size may be too small or there's infinite recursion."
        })
    elif signal:
        issues.append({
            'severity': 'CRITICAL',
            'category': 'crash',
            'message': f"JVM crash with signal {signal}."
        })
    
    # Check if crash in native code
    prob_frame = error_summary.get('problematic_frame', '')
    if prob_frame.startswith('C ') or prob_frame.startswith('V '):
        lib_match = re.search(r'\[([^\]]+)\]', prob_frame)
        lib_name = lib_match.group(1) if lib_match else 'unknown library'
        if prob_frame.startswith('V '):
            issues.append({
                'severity': 'CRITICAL',
                'category': 'jvm_bug',
                'message': f"Crash in JVM internal code ({lib_name}). This is likely a JVM bug. Check for known issues and consider upgrading."
            })
        else:
            issues.append({
                'severity': 'CRITICAL',
                'category': 'native_code',
                'message': f"Crash in native library: {lib_name}. Check for native memory corruption or library version issues."
            })
    elif prob_frame.startswith('j ') or prob_frame.startswith('J '):
        issues.append({
            'severity': 'CRITICAL',
            'category': 'java_code',
            'message': f"Crash in compiled Java code. Possible JIT compiler bug or unsafe memory access."
        })
    
    # OOM indicators
    if 'OutOfMemoryError' in text or 'insufficient memory' in text.lower():
        issues.append({
            'severity': 'CRITICAL',
            'category': 'oom',
            'message': "Crash related to OutOfMemoryError. The JVM ran out of memory."
        })
    
    # Check memory
    phys_free = memory_info.get('physical_free_mb', float('inf'))
    if phys_free < 100:
        issues.append({
            'severity': 'WARNING',
            'category': 'memory',
            'message': f"Very low free physical memory at crash time: {phys_free} MB"
        })
    
    result['issues'] = issues
    
    return result


def parse_elf_core(filepath):
    """Basic analysis of an ELF core dump file.
    For full analysis, jhsdb/gdb is required."""
    with open(filepath, 'rb') as f:
        magic = f.read(4)
    
    if magic != b'\x7fELF':
        return {
            'file': os.path.basename(filepath),
            'error': 'Not an ELF file',
            'type': 'unknown'
        }
    
    with open(filepath, 'rb') as f:
        data = f.read(64)  # ELF header
    
    result = {
        'file': os.path.basename(filepath),
        'file_size_bytes': os.path.getsize(filepath),
        'file_size_mb': round(os.path.getsize(filepath) / (1024 * 1024), 2),
        'type': 'elf_core',
    }
    
    # ELF class (32 or 64 bit)
    ei_class = data[4]
    result['elf_class'] = 'ELF64' if ei_class == 2 else 'ELF32'
    
    # Endianness
    ei_data = data[5]
    result['endianness'] = 'little-endian' if ei_data == 1 else 'big-endian'
    
    # ELF type
    if ei_data == 1:  # little-endian
        e_type = struct.unpack('<H', data[16:18])[0]
    else:
        e_type = struct.unpack('>H', data[16:18])[0]
    
    elf_types = {0: 'NONE', 1: 'REL', 2: 'EXEC', 3: 'DYN', 4: 'CORE'}
    result['elf_type'] = elf_types.get(e_type, f'unknown({e_type})')
    
    if e_type != 4:
        result['warning'] = 'This does not appear to be a core dump file (ELF type != CORE)'
    
    result['recommendation'] = (
        "For full analysis of this core dump, use JDK tools:\n"
        "  jhsdb jstack --core {file} --exe $(which java)\n"
        "  jhsdb jmap --heap --core {file} --exe $(which java)\n"
        "  jhsdb jmap --histo --core {file} --exe $(which java)\n"
        "Or use GDB:\n"
        "  gdb -c {file} $(which java)"
    ).format(file=os.path.basename(filepath))
    
    result['issues'] = [{
        'severity': 'CRITICAL',
        'category': 'crash',
        'message': f"Core dump file detected ({result['file_size_mb']} MB). The JVM process crashed. Use jhsdb or gdb for detailed analysis."
    }]
    
    return result


def parse_windows_minidump(filepath):
    """Basic analysis of a Windows minidump file."""
    with open(filepath, 'rb') as f:
        magic = f.read(4)
    
    if magic != b'MDMP':
        return {
            'file': os.path.basename(filepath),
            'error': 'Not a Windows minidump file',
            'type': 'unknown'
        }
    
    with open(filepath, 'rb') as f:
        data = f.read(32)
    
    result = {
        'file': os.path.basename(filepath),
        'file_size_bytes': os.path.getsize(filepath),
        'file_size_mb': round(os.path.getsize(filepath) / (1024 * 1024), 2),
        'type': 'windows_minidump',
    }
    
    # Version
    version = struct.unpack('<HH', data[4:8])
    result['version'] = f"{version[0]}.{version[1]}"
    
    # Number of streams
    num_streams = struct.unpack('<I', data[8:12])[0]
    result['stream_count'] = num_streams
    
    # Timestamp
    timestamp = struct.unpack('<I', data[16:20])[0]
    from datetime import datetime, timezone
    try:
        dt = datetime.fromtimestamp(timestamp, tz=timezone.utc)
        result['crash_time'] = dt.isoformat()
    except (OSError, ValueError, OverflowError):
        result['crash_timestamp'] = timestamp
    
    result['recommendation'] = (
        "For full analysis of this minidump, use:\n"
        "  WinDbg: .loadby sos clrjit; !clrstack; !dumpheap -stat\n"
        "  Or jhsdb on Windows:\n"
        "  jhsdb jstack --core {file} --exe java.exe"
    ).format(file=os.path.basename(filepath))
    
    result['issues'] = [{
        'severity': 'CRITICAL',
        'category': 'crash',
        'message': f"Windows minidump detected ({result['file_size_mb']} MB). The JVM process crashed."
    }]
    
    return result


def detect_and_parse(filepath):
    """Auto-detect file format and parse accordingly."""
    basename = os.path.basename(filepath)
    
    # Check if it's an hs_err log by filename pattern
    if basename.startswith('hs_err_pid') or basename.endswith('.log'):
        # Try reading as text first
        try:
            with open(filepath, 'r', errors='replace') as f:
                first_line = f.readline()
            if 'fatal error' in first_line.lower() or first_line.startswith('#'):
                return parse_hs_err_log(filepath)
        except Exception:
            pass
    
    # Check magic bytes
    with open(filepath, 'rb') as f:
        magic = f.read(4)
    
    if magic == b'\x7fELF':
        return parse_elf_core(filepath)
    elif magic == b'MDMP':
        return parse_windows_minidump(filepath)
    else:
        # Try as text (hs_err log)
        try:
            with open(filepath, 'r', errors='replace') as f:
                text = f.read(1000)
            if 'Java' in text or 'JRE' in text or 'fatal error' in text.lower() or 'SIGSEGV' in text:
                return parse_hs_err_log(filepath)
        except Exception:
            pass
    
    return {
        'file': basename,
        'error': 'Could not determine file format. Expected hs_err_pid*.log, .core (ELF), or .mdmp (Windows minidump).',
        'type': 'unknown',
        'issues': [{
            'severity': 'INFO',
            'category': 'format',
            'message': 'Unrecognized file format. Provide an hs_err_pid*.log, .core, or .mdmp file.'
        }]
    }


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 core_dump_analyzer.py <file>", file=sys.stderr)
        print("  Supports: hs_err_pid*.log, .core (ELF), .mdmp (Windows minidump)", file=sys.stderr)
        sys.exit(1)
    
    filepath = sys.argv[1]
    if not os.path.exists(filepath):
        print(f"Error: File not found: {filepath}", file=sys.stderr)
        sys.exit(1)
    
    result = detect_and_parse(filepath)
    print(json.dumps(result, indent=2, default=str))


if __name__ == '__main__':
    main()
